name: qr_studio
description: "QR Studio - Generate, scan, and manage QR codes in style."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  path_provider: ^2.1.5
  qr_code_scanner_plus: ^2.1.2
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  url_launcher: ^6.3.1
  lottie: ^3.3.1
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.5.2
  share_plus: ^10.1.4
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.4
  file_picker: ^8.1.7
  image: ^4.5.3
  zxing2: ^0.2.4
  package_info_plus: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  bloc_test: ^10.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/lottie/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logos/app_icon.png"
  adaptive_icon_background: "#6C63FF"

flutter_native_splash:
  color: "#6C63FF"
  color_dark: "#0F0F1A"
  image: "assets/logos/app_icon.png"
  android: true
  ios: false
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
